version: '3.8'

services:
    mariadb:
      container_name: mariadb
      env_file:
        - .env

      networks:
        - inception
      build:
        context: requirements/mariadb
        dockerfile: Dockerfile

      volumes:
        - /nfs/homes/gclement/Desktop/Inception/volumes/db:/var/lib/mysql
      expose:
        - "3306"
      restart: unless-stopped

    nginx:
      container_name: nginx
      image: nginx
      networks:
        - inception

      build:
        context: requirements/nginx
        dockerfile: Dockerfile

      volumes:
        - /nfs/homes/gclement/Desktop/Inception/volumes/wordpress:/var/www/wordpress

      ports:
        - "5000:5000"
      depends_on:
        - wordpress
      restart: on-failure

    wordpress:
      container_name: wordpress
      image: wordpress
      networks:
        - inception
      build:
        context: requirements/wordpress
        dockerfile: Dockerfile
      
      env_file:
        - .env
      
      volumes:
        - /nfs/homes/gclement/Desktop/Inception/volumes/wordpress:/var/www/wordpress
      
      depends_on:
        - mariadb
      restart: on-failure
      expose: 
        - "9000"

volumes:
    wordpress:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /nfs/homes/gclement/Desktop/Inception/volumes/wordpress
    mariadb:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /nfs/homes/gclement/Desktop/Inception/volumes/db
          
networks:
  inception:
    driver: bridge
